### PR TITLE
Update react-router w/ npm auto-update

### PR DESCRIPTION
**Pull request by renbaoshuo**

### CODE REVIEW

**Comment by MattIPv4** [comment]
cc #1289 #926 -- looks like we've got an existing use case of `ignoreVersions` in a config, a property we don't currently support

**Comment by renbaoshuo** [comment]
The location of `react-router.production.min.js` has changed since `react-router@6.4.0`. I just updated it and hope you will review this PR again.

**Comment by renbaoshuo** [comment]
@MattIPv4

**Review by MattIPv4 — APPROVED** [review]
LGTM, ty (and looks like the removal of the `ignoreVersions` is safe now, the `latest` version doesn't seem to be on NPM now)

**Pull request merged**
