### PR TITLE
Add jose w/ git auto-update

### LINKED ISSUE #869: Add: jose
### Library name

jose

### Library license

https://github.com/panva/jose/blob/main/LICENSE.md

### Library source

https://github.com/panva/jose/tree/v4.0.2

---

Notes:

- only tagged commits include the `dist` folder
- the browser entry point is only `./dist/browser/index.js`
- types (should they be applicable) are in `./dist/types/index.d.ts`

### PR DESCRIPTION
**Pull request by panva**
Adding jose using git auto-update from git://github.com/panva/jose.git

resolves #869

### CODE REVIEW

**Comment by panva** [comment]
> Looking at your browser dist directory, it seems that this is ESM code? Is this project something that will only work in browsers that support modules?

correct

> (Fwiw, I was expecting to find a single, bundled file with cjs/umd support)

I can add a single ESM bundle

**Comment by panva** [comment]
> Is `index.js` the recommended default file for folks to use?

yes

**Comment by panva** [comment]
@MattIPv4 thank you for walking me through this.

May I inquire about the frequency of auto-updates, and if I need to publish a new release now to have the package published?

**Comment by MattIPv4** [comment]
You shouldn't need to publish a new version, we'll detect the most recent few you already have. The auto-update runs every 2 hours or so iirc, as it takes about that long to check all the packages we have.

**Pull request merged**
