### PR TITLE
update ci

### PR DESCRIPTION
**Pull request by xtuc**

### CODE REVIEW

**Comment by robocdnjs** [comment]
packages/s/spinkit.json: error: not implemented yet

**Comment by robocdnjs** [comment]
panic: exit status 1

goroutine 1 [running]:
github.com/cdnjs/tools/util.Check(...)
 /home/runner/work/tools/tools/util/check.go:9
github.com/cdnjs/tools/util.ListFilesGlob(0xc000268840, 0x18, 0xc0000a43a0, 0xc, 0x18, 0xc000082dd0, 0x7259f0)
 /home/runner/work/tools/tools/util/fileglob.go:28 +0x708
github.com/cdnjs/tools/packages.(*Package).NpmFilesFrom(0xc0000c26c0, 0xc0000177a0, 0x18, 0x36, 0xc0000177a0, 0x18)
 /home/runner/work/tools/tools/packages/packages.go:113 +0x227
main.showFiles(0x7ffc58a3a4d2, 0x17)
 /home/runner/work/tools/tools/cmd/checker/main.go:64 +0x21a
main.main()
 /home/runner/work/tools/tools/cmd/checker/main.go:41 +0x22f

**Comment by robocdnjs** [comment]
Tests passed.
The following files will be published:

**Comment by robocdnjs** [comment]
packages/s/spinkit.json: download https://registry.npmjs.org/spinkit/-/spinkit-1.1.0.tgz in /tmp/npmtarball052692061

**Comment by robocdnjs** [comment]
packages/s/spinkit.json: download https://registry.npmjs.org/spinkit/-/spinkit-2.0.1.tgz in /tmp/npmtarball554320001

**Comment by robocdnjs** [comment]
packages/s/spinkit.json: download https://registry.npmjs.org/spinkit/-/spinkit-1.2.4.tgz in /tmp/npmtarball343012249

**Comment by robocdnjs** [comment]
Tests passed.
The following files will be published:

**Comment by robocdnjs** [comment]
Tests passed.
The following files will be published:
match spinkit*.css in /tmp/npmtarball813737917
[{ }]

**Comment by robocdnjs** [comment]
packages/s/spinkit.json: {2.0.1 https://registry.npmjs.org/spinkit/-/spinkit-2.0.1.tgz}:
packages/s/spinkit.json: [{spinkit.css spinkit.css} {spinkit.min.css spinkit.min.css}]

**Comment by robocdnjs** [comment]
Tests passed.
The following files will be published:

**Comment by robocdnjs** [comment]
Tests passed.
The following files will be published:

**Comment by robocdnjs** [comment]
Tests passed.
The following files will be published:

**Comment by robocdnjs** [comment]
Tests passed.
The following files will be published:

**Comment by robocdnjs** [comment]
Tests passed.
The following files will be published:

**Comment by robocdnjs** [comment]
Tests passed.
The following files will be published:

**Comment by robocdnjs** [comment]
Lint failed:
packages/s/spinkit.json: error: failed to parse packages/s/spinkit.json: invalid character 'f' looking for beginning of object key string

**Comment by robocdnjs** [comment]
Tests passed.
The following files will be published:

**Comment by robocdnjs** [comment]
Tests passed.
The following files will be published:

**Comment by robocdnjs** [comment]
Lint failed:

**Comment by robocdnjs** [comment]
Tests passed.
The following files will be published:
  packages/s/spinkit.json: 2.0.0:
packages/s/spinkit.json: spinkit.css
packages/s/spinkit.json: spinkit.min.css

**Comment by robocdnjs** [comment]
CI failed:
packages/s/spinkit.json: error: failed to parse packages/s/spinkit.json: invalid character '"' after object key:value pair

**Comment by robocdnjs** [comment]
Tests passed.
The following files will be published:
  packages/s/spinkit.json: 1.2.0/

**Comment by robocdnjs** [comment]
Tests passed. The following files will be published:
  packages/s/spinkit.json: 1.2.5 -

**Comment by robocdnjs** [comment]
Tests passed.
The following files will be published:
  packages/s/spinkit.json: 2.0.1:
packages/s/spinkit.json: spinkit.css
packages/s/spinkit.json: spinkit.min.css

**Comment by MattIPv4** [comment]
@xtuc something like:

**Tests passed.**
The following files will be published:
```text
packages/s/spinkit.json: 2.0.1:
packages/s/spinkit.json: spinkit.css
packages/s/spinkit.json: spinkit.min.css
```

**Comment by robocdnjs** [comment]
Tests passed.
The following files will be published:

**Pull request merged**
