### PR TITLE
Add codemirror-spell-checker w/ npm auto-update

### LINKED ISSUE #255: [Request] Add codemirror-spell-checker
**Library name:** codemirror-spell-checker
**Git repository url:** https://github.com/NextStepWebs/codemirror-spell-checker
**npm package name or url** (if there is one) : codemirror-spell-checker 
**License (List them all if it's multiple):** MIT
**Official homepage:** https://nextstepwebs.github.io/codemirror-spell-checker/

cc @ jackycute

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/44236347-request-add-codemirror-spell-checker?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F32893&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by xtuc**
Resolves #255

### CODE REVIEW

**Comment by robocdnjs** [comment]
**Tests passed.**
Preview for `packages/c/codemirror-spell-checker.json`
Last version (1.1.2):
```
en_US.aff
en_US.dic
spell-checker.min.css
spell-checker.min.js
```
10 Last version:
```
1.1.2: 4 file(s) matched
1.1.1: 4 file(s) matched
1.1.0: 4 file(s) matched
```

**Comment by robocdnjs** [comment]
**Tests passed.**

**Comment by robocdnjs** [comment]
**Tests passed.**

**Comment by robocdnjs** [comment]
**Tests passed.**

Preview for `packages/c/codemirror-spell-checker.json`
Last version (1.1.2):
```
en_US.aff
en_US.dic
spell-checker.min.css
spell-checker.min.js
```

10 last versions:
- 1.1.2: 4 file(s) matched :heavy_check_mark:
- 1.1.1: 4 file(s) matched :heavy_check_mark:
- 1.1.0: 4 file(s) matched :heavy_check_mark:

**Comment by robocdnjs** [comment]
**Tests passed.**

Preview for `packages/c/codemirror-spell-checker.json`
Last version (1.1.2):
```
en_US.aff
en_US.dic
spell-checker.min.css
spell-checker.min.js
```

10 last versions:
- 1.1.2: 4 file(s) matched :heavy_check_mark:
- 1.1.1: 4 file(s) matched :heavy_check_mark:
- 1.1.0: 4 file(s) matched :heavy_check_mark:

**Review by botreview — APPROVED** [review]
LGTM

**Pull request closed without merging**
