### PR TITLE
Bulk 1: Update X w/ npm auto-update

### PR DESCRIPTION
**Pull request by klausenbusk**
This was done by-hand with help from `curl -s $(npm view X dist.tarball) | tar -tvzf -`

Refs #302

### CODE REVIEW

**Comment by MattIPv4** [comment]
I would much prefer these changes as a single JSON file per PR, please, so that we can effectively review each one and maintain a clear repo history/blame.

**Comment by klausenbusk** [comment]
>  I would much prefer these changes as a single JSON file per PR, please, so that we can effectively review each one and maintain a clear repo history/blame.

Why would the history/blame be less clear? Are you squashing the commits?

**Comment by MattIPv4** [comment]
Yes, all commits to master are squashed, so the general practice is one PR / one commit to master for each package change :)

**Comment by klausenbusk** [comment]
Do you want me to split this PR?

**Comment by MattIPv4** [comment]
Yes, if you could, please -- so that we have a PR for each package being modified. Thank you :)

**Comment by klausenbusk** [comment]
Superseded by: #311, #312, #313, #314 and #315

**Pull request closed without merging**
