### PR TITLE
Add SopPlayer

### PR DESCRIPTION
**Pull request by SH20RAJ**
Sopplayer is a sleek and feature-rich HTML5 video player that enhances the visual experience of videos on web pages. It offers compatibility across devices and browsers, supporting various video formats. With intuitive controls and customizable options, Sopplayer provides a seamless and captivating playback experience for viewers.

### CODE REVIEW

**Comment by SH20RAJ** [comment]
Hii

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
Your PR should be adding a single JSON library configuration file, which will include an auto-update stanza telling us where to fetch your library files from You should not be including any other files in your PR. Please take a read through https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md

**Comment by MattIPv4** [comment]
No progress, closing.

**Comment by SH20RAJ** [comment]
> Your PR should be adding a single JSON library configuration file, which will include an auto-update stanza telling us where to fetch your library files from You should not be including any other files in your PR. Please take a read through https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md

**Comment by SH20RAJ** [comment]
> Your PR should be adding a single JSON library configuration file, which will include an auto-update stanza telling us where to fetch your library files from You should not be including any other files in your PR. Please take a read through https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md

  "autoupdate": {
    "source": "npm",
    "target": "function-plot",
    "fileMap": [
      {
        "basePath": "dist",
        "files": [
          "*.js",
          "*.css"
        ]
      }
    ]
  }

I want to add the whole repository to be fetched.

**Pull request closed without merging**
