### PR TITLE
add react-markdown-editor-lite

### PR DESCRIPTION
**Pull request by xtuc**

### CODE REVIEW

**Comment by robocdnjs** [comment]
**Tests failed:**
```text
packages/a/react-markdown-editor-lite.json: error: .version should be empty

```

**Comment by robocdnjs** [comment]
**Tests passed.**
The following files will be published:
```text
  packages/a/react-markdown-editor-lite.json: 1.1.0-beta.0:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
```

**Comment by xtuc** [comment]
I noticed that I put it into the wrong folder, the bot should ensure that. packages/a/react-markdown-editor-lite.json

**Comment by sylingd** [comment]
There seems to be no major problem, but why the bot got version `1.1.0-beta.0`

**Comment by xtuc** [comment]
@sylingd the bot should get the last 10 versions in semver order, the comment only displays the last one. I think that's confusing and i will change that

**Comment by robocdnjs** [comment]
**Tests passed.**
The following files will be published:
```text
  packages/a/react-markdown-editor-lite.json: 1.1.0:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: 1.1.2:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: 0.5.1:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: index.nostyle.js
packages/a/react-markdown-editor-lite.json: 1.0.1:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: 1.1.0-beta.0:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: 0.3.5:
packages/a/react-markdown-editor-lite.json: react-markdown-editor-lite.min.js
packages/a/react-markdown-editor-lite.json: 0.3.7:
packages/a/react-markdown-editor-lite.json: react-markdown-editor-lite.min.js
packages/a/react-markdown-editor-lite.json: 0.3.9:
packages/a/react-markdown-editor-lite.json: react-markdown-editor-lite.min.js
packages/a/react-markdown-editor-lite.json: 0.4.4:
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: 0.5.2:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: index.nostyle.js
```

**Comment by robocdnjs** [comment]
**Tests passed.**
The following files will be published:
```text
  packages/a/react-markdown-editor-lite.json: 0.5.2:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: index.nostyle.js
packages/a/react-markdown-editor-lite.json: 0.6.0:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: 0.6.1:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: 1.0.0:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: 1.0.1:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: 1.0.2:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: 1.1.0-beta.0:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: 1.1.0:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: 1.1.1:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: 1.1.2:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
```

**Comment by xtuc** [comment]
@MattIPv4 do you think we should only show the last version?

The bot will push 10 versions each run and starting from the first. Showing all the versions in a comment might be too big?

**Comment by MattIPv4** [comment]
@xtuc If you want to get fancy, show the most recent version, and then hide the other versions with the summary/details html tag:

```
packages/a/react-markdown-editor-lite.json: 1.1.2:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
```

<details>
<summary>Older versions will also be published:</summary>
<pre><code>packages/a/react-markdown-editor-lite.json: 0.5.2:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: index.nostyle.js
packages/a/react-markdown-editor-lite.json: 0.6.0:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: 0.6.1:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
...</code></pre>
</details>

image

**Comment by xtuc** [comment]
I like that idea. I also want to apply the pattern to all the previous version to check that we will actually copy files.

I suspect that I need to fix the output interpretation by GitHub Action thing first to make something more fancy

**Comment by MattIPv4** [comment]
@xtuc it might be easier almost to have the linter make the comment itself, so you don't need to worry about passing things around in actions?

**Comment by xtuc** [comment]
Ideally I would like to print multiple the the `##set-output...` but I haven't tried yet if that's support. Multiline aren't really...

**Comment by robocdnjs** [comment]
**Tests passed.**
The following files will be published:
```text
  packages/a/react-markdown-editor-lite.json: 1.1.2:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: 0.5.2: 3 file(s) matched
packages/a/react-markdown-editor-lite.json: 0.6.0: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 0.6.1: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.0.0: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.0.1: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.0.2: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.1.0-beta.0: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.1.0: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.1.1: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.1.2: 2 file(s) matched
```

**Comment by robocdnjs** [comment]
**Tests passed.**
packages/a/react-markdown-editor-lite.json: Last version:
```
packages/a/react-markdown-editor-lite.json: 0.5.2:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
packages/a/react-markdown-editor-lite.json: index.nostyle.js
```
packages/a/react-markdown-editor-lite.json: 10 Last version:
```
packages/a/react-markdown-editor-lite.json: 1.1.2: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.1.1: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.1.0: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.1.0-beta.0: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.0.2: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.0.1: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.0.0: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 0.6.1: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 0.6.0: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 0.5.2: 3 file(s) matched
```

**Comment by robocdnjs** [comment]
**Tests passed.**
Preview for `packages/a/react-markdown-editor-lite.json`
Last version:
```
packages/a/react-markdown-editor-lite.json: 1.1.2:
packages/a/react-markdown-editor-lite.json: index.css
packages/a/react-markdown-editor-lite.json: index.js
```
10 Last version:
```
packages/a/react-markdown-editor-lite.json: 1.1.2: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.1.1: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.1.0: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.1.0-beta.0: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.0.2: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.0.1: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 1.0.0: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 0.6.1: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 0.6.0: 2 file(s) matched
packages/a/react-markdown-editor-lite.json: 0.5.2: 3 file(s) matched
```

**Comment by robocdnjs** [comment]
**Tests passed.**
Preview for `packages/a/react-markdown-editor-lite.json`
Last version (1.1.2):
```
index.css
index.js
```
10 Last version:
```
1.1.2: 2 file(s) matched
1.1.1: 2 file(s) matched
1.1.0: 2 file(s) matched
1.1.0-beta.0: 2 file(s) matched
1.0.2: 2 file(s) matched
1.0.1: 2 file(s) matched
1.0.0: 2 file(s) matched
0.6.1: 2 file(s) matched
0.6.0: 2 file(s) matched
0.5.2: 3 file(s) matched
```

**Pull request merged**
