### PR TITLE
Add hyperjump-json-schema w/ npm auto-update

### LINKED ISSUE #1716: Add: @hyperjump/json-schema
### Library name

@hyperjump/json-schema

### Library license

https://github.com/hyperjump-io/json-schema/blob/main/LICENSE

### Library source

https://www.npmjs.com/package/@hyperjump/json-schema

### Files to include

\*

### PR DESCRIPTION
**Pull request by jeremyfiel**
closes #1716

### CODE REVIEW

**Comment by jeremyfiel** [comment]
@MattIPv4  not sure why the file name is failing. It has all alpha characters described in the regex. Can you advise?

**Comment by jeremyfiel** [comment]
I'm not sure why it's not finding any files. can you help on this one?

**Comment by MattIPv4** [comment]
`*` as the basePath looks odd to me, I suspect you want `` (empty) for the root? Also, I'd recommended avoiding using a wildcard for the files, generally, we want folks to at least scope it to a specific set of extensions.

**Comment by jeremyfiel** [comment]
for these paths.. Do I need to add both variations to pickup the .js in the first level and also recursively in the nested folders.  what do you think? 

```
"draft-2019-09/**/*.js",
"draft-2020-12/**/*.js",
```

```
"draft-2019-09/*.js",
"draft-2020-12/*.js",
```

**Comment by MattIPv4** [comment]
I believe `**/*` should capture everything -- you can play around at https://do.co/glob-tool

**Comment by jeremyfiel** [comment]
oh ya. seems to work ok.  thanks.

**Comment by jeremyfiel** [comment]
ok, this is ready when you are.

**Review by MattIPv4 — APPROVED** [review]
LGTM, with the caveat that this is a module, not a bundled library.

**Pull request merged**
