### PR TITLE
Add hexo-generator-searchdb w/ npm auto-update

### LINKED ISSUE #1060: Add: hexo-generator-searchdb
### Library name

hexo-generator-searchdb

### Library license

https://github.com/next-theme/hexo-generator-searchdb/blob/main/LICENSE

### Library source

https://www.npmjs.com/package/hexo-generator-searchdb

### Files to include

- [search.js](https://github.com/next-theme/hexo-generator-searchdb/blob/main/dist/search.js)

### PR DESCRIPTION
**Pull request by MattIPv4**
Adding hexo-generator-searchdb using npm auto-update from hexo-generator-searchdb.

Resolves #1060.

### CODE REVIEW

**Review by MattIPv4 — COMMENTED** [review]
lgtm

**Comment by leirock** [comment]
@MattIPv4 seems cdnjs cannot find hexo-generator-searchdb. 404 not found on the website of cdnjs

**Comment by MattIPv4** [comment]
Looking at [the logs](https://github.com/cdnjs/logs/tree/prod/packages/h/hexo-generator-searchdb), the bot so far has only processed older versions of the library, which I suspect don't have files in the expected place. The config should be valid for 1.4.0 once it pulls that in.

**Comment by leirock** [comment]
thx. It is available now.

**Pull request merged**
