### PR TITLE
Add cronstrue w/ npm auto-update

### PR DESCRIPTION
**Pull request by jtroe**

### CODE REVIEW

**Comment by jtroe** [comment]
Will this be reviewed soon? 😄

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
:wave: Please could you update the file to have consistent 2-space indentation?

It also looks like the file ending is a bit unhappy currently

**Comment by jtroe** [comment]
Fixed.  Thanks!

**Review by MattIPv4 — APPROVED** [review]
lgtm

**Pull request merged**
