### PR TITLE
Add buefy w/ npm auto-update

### PR DESCRIPTION
**Pull request by MattIPv4**
Adding buefy using npm auto-update from NPM package buefy.

Resolves https://github.com/cdnjs/cdnjs/issues/12584.

### CODE REVIEW

**Comment by robocdnjs** [comment]
**Tests failed:**
```text

Preview for `packages/b/buefy.json`
Last version (1.0.0):
```
match **/*.@(js|css|json) in /tmp/npmtarball980746304/dist but doesn't exists
packages/b/buefy.json: error: no files to copy
```

**Comment by robocdnjs** [comment]
**Tests failed:**
```text

Preview for `packages/b/buefy.json`
Last version (1.0.0):
```
match **/*.@(js|css|json) in /tmp/npmtarball831416414/dist but doesn't exists
packages/b/buefy.json: error: no files to copy
```

**Comment by MattIPv4** [comment]
@xtuc it looks like this package has some incorrect semver going on. 1.0.0 was their initial release three years ago, they're now on 0.8.17: https://www.npmjs.com/package/buefy

**Comment by xtuc** [comment]
@MattIPv4 technically the bot will pick every versions, probably in the wrong order because we sort them by semver as @robocdnjs showed. I don't know how to fix that because npmjs doesn't timestamp the versions

**Comment by robocdnjs** [comment]
**Tests failed:**

Preview for `packages/b/buefy.json`
Last version (1.0.0):
```
match **/*.@(js|css|json) in /tmp/npmtarball560941295/dist but doesn't exists
packages/b/buefy.json: error: no files to copy

**Comment by robocdnjs** [comment]
**Tests failed:**

Preview for `packages/b/buefy.json`
Last version (1.0.0):
match **/*.@(js|css|json) in /tmp/npmtarball117507544/dist but doesn't exists
packages/b/buefy.json: error: No files will be published for this version; you can debug using
dir /tmp/npmtarball117507544
f package.json
[Click here to debug your glob pattern `**/*.@(js|css|json)`](https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2A%2A%2F%2A.%40%28js%7Ccss%7Cjson%29&matches=true&tests=package.json&tests=)
.

**Comment by robocdnjs** [comment]
**Tests failed:**

Preview for `packages/b/buefy.json`
Last version (1.0.0):
match **/*.@(js|css|json) in /tmp/npmtarball700156304/dist but doesn't exists
packages/b/buefy.json: error: No files will be published for this version; you can debug using
[Click here to debug your glob pattern `**/*.@(js|css|json)`](https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2A%2A%2F%2A.%40%28js%7Ccss%7Cjson%29&matches=true&tests=package.json&tests=).

**Pull request merged**
