### PR TITLE
Cleanup

### LINKED ISSUE #253: Cleanup commit
As we have now completed the migration from cdnjs/cdnjs to here for all package configurations, we need to make a cleanup commit to this repository to address some small remaining issues with the configuration JSON files here.

- Remove `version` attr from all JSON files
- Migrate `npmName/npmFileMap` properties to the new `autoupdate` format
- Format all JSON files nicely (2 space indents)

cc https://github.com/cdnjs/cdnjs/issues/13652

### PR DESCRIPTION
**Pull request by klausenbusk**
Fix #253 

> As we have now completed the migration from cdnjs/cdnjs to here for all package configurations, we need to make a cleanup commit to this repository to address some small remaining issues with the configuration JSON files here.
> 
>     * Remove `version` attr from all JSON files
> 
>     * Migrate `npmName/npmFileMap` properties to the new `autoupdate` format
> 
>     * Format all JSON files nicely (2 space indents)
> 
> 
> cc [cdnjs/cdnjs#13652](https://github.com/cdnjs/cdnjs/issues/13652)

### CODE REVIEW

**Comment by klausenbusk** [comment]
I don't think the CI did anything.

**Comment by MattIPv4** [comment]
Wow! Amazing PR, thank you very much from all of us! <3

We're going to have a look tomorrow at what exactly the CI is doing (or rather, not doing) here, it definitely should be able to run and validate this PR fully.

**Comment by xtuc** [comment]
thanks for the work @klausenbusk  and the reproducable commands.

**Comment by MattIPv4** [comment]
Hey @klausenbusk, would you be interested in submitting a similar PR on cdnjs/cdnjs? We'd want the npmName/npmFileMap transformation & the pretty printing, but we don't need to remove version over there.

**Comment by klausenbusk** [comment]
> Hey @klausenbusk, would you be interested in submitting a similar PR on 
> cdnjs/cdnjs? We'd want the npmName/npmFileMap transformation & the pretty 
> printing, but we don't need to remove version over there.
Sure, I will do it later tonight.

**Comment by klausenbusk** [comment]
> Sure, I will do it later tonight.

See PR: https://github.com/cdnjs/cdnjs/pull/13994

**Pull request merged**
