### PR TITLE
Add ovh w/ npm auto-update

### PR DESCRIPTION
**Pull request by martinez-hugo**

### CODE REVIEW

**Comment by martinez-hugo** [comment]
Issue #1466

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
A few change requests here:

1. Your entire file seems to have odd indenting (everything seems to have an extra 2-space indent, including the first line).

2. Your file ending seems to be rather odd, can you check that you have a standard single newline at the end of the file with no trailing whitespace?

3. You indicate you are trying to add the `ovh` package from NPM, but your autoupdate config is currently targeting the `open` package?

4. Inspecting the `ovh` package locally, both the es5 & es6 files in `lib` make use of Node.js `require` calls, which do not work on the web? Is there a different web-compatible bundle that you are intending to add here?

**Comment by martinez-hugo** [comment]
Hi ! Normally I fix all 3 first points

But for 4th point, I've checked repo but there are not other file of this module without require
How can we do ?

**Comment by MattIPv4** [comment]
If you are looking to use this package on the web, you will need to work with the maintainers of the package to have a web-compatible version published, which could then be added to cdnjs.

**Comment by martinez-hugo** [comment]
Does this module is better ?
https://www.npmjs.com/package/@ovh-api/sms

**Comment by MattIPv4** [comment]
No, and you can check this very easily locally rather than asking me...

```shell 
npm i @ovh-api/sms
cd node_modules/@ovh-api/sms
ls # Observe index.js and cjs/
cat index.js # Observe `import` calls
cd cjs
ls # Observe index.js
cat index.js # Observe `require` calls
```

**Comment by MattIPv4** [comment]
No progress, closing.

**Pull request closed without merging**
