### PR TITLE
Update react-inputs-validation w/ npm auto-update

### PR DESCRIPTION
**Pull request by edwardfxiao**
Update the ```homepage```, ```repository URL```, and ```description``` of``` react-inputs-validation.json``` since the GitHub username has changed.

### CODE REVIEW

**Review by MattIPv4 — APPROVED** [review]
LGTM

**Comment by edwardfxiao** [comment]
@MattIPv4 Hi, I don't see these two change
image
and the https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/react-inputs-validation/package.json has not been updated either.

Is there anything else I should do to get them updated?

**Comment by MattIPv4** [comment]
The data won't update until a new version of the library is published :)

**Comment by edwardfxiao** [comment]
@MattIPv4 Thank you for the clarification

**Comment by edwardfxiao** [comment]
@MattIPv4
I just updated a new version of 4.9.2 and https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/react-inputs-validation has been updated but [package.json](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/react-inputs-validation/package.json) still has not changed, any suggestion?

**Comment by MattIPv4** [comment]
I don't think we update those top-level JSON files anymore, but you can see that the updated JSON is present for the new version: https://github.com/cdnjs/logs/commit/b061c3c090eb6f9213a76d463599497cdf06d5c9

**Comment by edwardfxiao** [comment]
> I don't think we update those top-level JSON files anymore

The wrong top-level JSON file takes my ```homepage``` to a ```404``` page. It would be nice if there is a way to correct it,
I wonder if the team will have any plan for this?

**Comment by edwardfxiao** [comment]
To me, [cdnjs.com](https://cdnjs.com/) is still a very serious official site for libraries, and there are many other websites all over the world that are mirroring from it. 

So I personally would love it keep the information accurate.

**Comment by MattIPv4** [comment]
Yes, I agree -- cdnjs.com is driven by data in our KV store, not by the cdnjs/cdnjs repository.

**Comment by edwardfxiao** [comment]
@MattIPv4 Sorry I was confused about the relationships of ```cdn/cdn``` ```cdn website```

I understand what you saying now.

- the top-level [package.js](https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/react-inputs-validation/package.json) on ```cdn/cdn``` repository supposedly doesn't have an effect on [cdnjs.com](https://cdnjs.com/) anymore because it is more like a backup now
- the data in KV store takes over the responsibility to the [cdnjs.com](https://cdnjs.com/), and the log does show the package.json file has been updated

Interestingly that the ```description``` on the response of the search box has been updated whereas on the detail page doesn't.

Do you think I could open an issue to track this?





image

**Comment by MattIPv4** [comment]
Sure -- please open it in cdnjs/api-server (it looks like https://api.cdnjs.com/libraries/react-inputs-validation doesn't have the new info)

**Pull request merged**
