### PR TITLE
Add epijs w/ git auto-update

### PR DESCRIPTION
**Pull request by Quantalabs**
Adds the EpiJS package to cdnjs

### CODE REVIEW

**Review by MattIPv4 — APPROVED** [review]
Lgtm

**Comment by Quantalabs** [comment]
Is it just my end, or does cdnjs only show the `pre.min.js` file, when it should be showing the `index.min.js` file?

**Comment by MattIPv4** [comment]
It looks like the 1.3.x versions haven't been loaded yet -- the latest version on the site currently is [1.2.1](https://cdnjs.com/libraries/epijs/1.2.1), which has the correct files from that tag in your repo: https://github.com/Quantalabs/EpiJS/tree/v1.2.1/web

**Comment by Quantalabs** [comment]
Oh, I see, I still don't think that the loading of the other files are necessary, and fixed it in #780, and I also fixed a typo.

**Pull request merged**
