### PR TITLE
Update jquery-validation-unobtrusive w/ npm auto-update

### PR DESCRIPTION
**Pull request by mkArtakMSFT**
Addresses https://github.com/cdnjs/packages/issues/1246

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
Hi @MattIPv4. Can this PR be merged? I think there isn't more than this to be done for a license update.

**Comment by MattIPv4** [comment]
Hey! Currently recovering from covid, but I'll try to go through all the PRs here as soon as I can :)

**Comment by mkArtakMSFT** [comment]
No problem, hope you'll get better soon!

**Review by MattIPv4 — APPROVED** [review]
LGTM, ty

**Pull request merged**
