### PR TITLE
add serializr

### PR DESCRIPTION
**Pull request by xtuc**

### CODE REVIEW

**Comment by robocdnjs** [comment]
**Tests failed:**
```text

packages/s/serializr.json: 1.1.8:
match **/*.@(js|ts) in /tmp/npmtarball486421519/lib but doesn't exists
packages/s/serializr.json: error: no files to copy
```

**Comment by xtuc** [comment]
@MattIPv4 `/lib` doesn't exist apparently?

**Comment by MattIPv4** [comment]
It's there for me in the package:
image

**Comment by robocdnjs** [comment]
**Tests passed.**
The following files will be published:
```text
  packages/s/serializr.json: 1.5.1:
packages/s/serializr.json: es/serializr.js
packages/s/serializr.json: serializr.js
packages/s/serializr.json: serializr.min.js
packages/s/serializr.json: 1.5.2:
packages/s/serializr.json: es/serializr.js
packages/s/serializr.json: serializr.js
packages/s/serializr.json: serializr.min.js
packages/s/serializr.json: 1.5.3:
packages/s/serializr.json: es/serializr.js
packages/s/serializr.json: serializr.js
packages/s/serializr.json: serializr.min.js
packages/s/serializr.json: 1.5.4:
packages/s/serializr.json: es/serializr.js
packages/s/serializr.json: serializr.js
packages/s/serializr.json: serializr.min.js
packages/s/serializr.json: 2.0.0-beta1:
packages/s/serializr.json: api/createModelSchema.d.ts
packages/s/serializr.json: api/createSimpleSchema.d.ts
packages/s/serializr.json: api/getDefaultModelSchema.d.ts
packages/s/serializr.json: api/serializable.d.ts
packages/s/serializr.json: api/setDefaultModelSchema.d.ts
packages/s/serializr.json: api/types.d.ts
packages/s/serializr.json: constants.d.ts
packages/s/serializr.json: core/cancelDeserialize.d.ts
packages/s/serializr.json: core/Context.d.ts
packages/s/serializr.json: core/deserialize.d.ts
packages/s/serializr.json: core/serialize.d.ts
packages/s/serializr.json: core/serializeAll.d.ts
packages/s/serializr.json: core/update.d.ts
packages/s/serializr.json: es/serializr.js
packages/s/serializr.json: es/serializr.min.js
packages/s/serializr.json: serializr.d.ts
packages/s/serializr.json: serializr.js
packages/s/serializr.json: serializr.min.js
packages/s/serializr.json: types/alias.d.ts
packages/s/serializr.json: types/custom.d.ts
packages/s/serializr.json: types/date.d.ts
packages/s/serializr.json: types/identifier.d.ts
packages/s/serializr.json: types/list.d.ts
packages/s/serializr.json: types/map.d.ts
packages/s/serializr.json: types/mapAsArray.d.ts
packages/s/serializr.json: types/object.d.ts
packages/s/serializr.json: types/optional.d.ts
packages/s/serializr.json: types/primitive.d.ts
packages/s/serializr.json: types/raw.d.ts
packages/s/serializr.json: types/reference.d.ts
packages/s/serializr.json: utils/invariant.d.ts
packages/s/serializr.json: utils/utils.d.ts
packages/s/serializr.json: 2.0.0-beta2:
packages/s/serializr.json: api/createModelSchema.d.ts
packages/s/serializr.json: api/createSimpleSchema.d.ts
packages/s/serializr.json: api/getDefaultModelSchema.d.ts
packages/s/serializr.json: api/serializable.d.ts
packages/s/serializr.json: api/setDefaultModelSchema.d.ts
packages/s/serializr.json: api/types.d.ts
packages/s/serializr.json: constants.d.ts
packages/s/serializr.json: core/cancelDeserialize.d.ts
packages/s/serializr.json: core/Context.d.ts
packages/s/serializr.json: core/deserialize.d.ts
packages/s/serializr.json: core/serialize.d.ts
packages/s/serializr.json: core/serializeAll.d.ts
packages/s/serializr.json: core/update.d.ts
packages/s/serializr.json: es/serializr.js
packages/s/serializr.json: es/serializr.min.js
packages/s/serializr.json: serializr.d.ts
packages/s/serializr.json: serializr.js
packages/s/serializr.json: serializr.min.js
packages/s/serializr.json: types/alias.d.ts
packages/s/serializr.json: types/custom.d.ts
packages/s/serializr.json: types/date.d.ts
packages/s/serializr.json: types/identifier.d.ts
packages/s/serializr.json: types/list.d.ts
packages/s/serializr.json: types/map.d.ts
packages/s/serializr.json: types/mapAsArray.d.ts
packages/s/serializr.json: types/object.d.ts
packages/s/serializr.json: types/optional.d.ts
packages/s/serializr.json: types/poly.d.ts
packages/s/serializr.json: types/primitive.d.ts
packages/s/serializr.json: types/raw.d.ts
packages/s/serializr.json: types/reference.d.ts
packages/s/serializr.json: utils/invariant.d.ts
packages/s/serializr.json: utils/utils.d.ts
packages/s/serializr.json: 2.0.0:
packages/s/serializr.json: api/createModelSchema.d.ts
packages/s/serializr.json: api/createSimpleSchema.d.ts
packages/s/serializr.json: api/getDefaultModelSchema.d.ts
packages/s/serializr.json: api/serializable.d.ts
packages/s/serializr.json: api/setDefaultModelSchema.d.ts
packages/s/serializr.json: api/types.d.ts
packages/s/serializr.json: constants.d.ts
packages/s/serializr.json: core/cancelDeserialize.d.ts
packages/s/serializr.json: core/Context.d.ts
packages/s/serializr.json: core/deserialize.d.ts
packages/s/serializr.json: core/serialize.d.ts
packages/s/serializr.json: core/serializeAll.d.ts
packages/s/serializr.json: core/update.d.ts
packages/s/serializr.json: es/serializr.js
packages/s/serializr.json: es/serializr.min.js
packages/s/serializr.json: serializr.d.ts
packages/s/serializr.json: serializr.js
packages/s/serializr.json: serializr.min.js
packages/s/serializr.json: types/alias.d.ts
packages/s/serializr.json: types/custom.d.ts
packages/s/serializr.json: types/date.d.ts
packages/s/serializr.json: types/identifier.d.ts
packages/s/serializr.json: types/list.d.ts
packages/s/serializr.json: types/map.d.ts
packages/s/serializr.json: types/mapAsArray.d.ts
packages/s/serializr.json: types/object.d.ts
packages/s/serializr.json: types/optional.d.ts
packages/s/serializr.json: types/primitive.d.ts
packages/s/serializr.json: types/raw.d.ts
packages/s/serializr.json: types/reference.d.ts
packages/s/serializr.json: utils/invariant.d.ts
packages/s/serializr.json: utils/utils.d.ts
packages/s/serializr.json: 2.0.1:
packages/s/serializr.json: api/createModelSchema.d.ts
packages/s/serializr.json: api/createSimpleSchema.d.ts
packages/s/serializr.json: api/getDefaultModelSchema.d.ts
packages/s/serializr.json: api/serializable.d.ts
packages/s/serializr.json: api/setDefaultModelSchema.d.ts
packages/s/serializr.json: api/types.d.ts
packages/s/serializr.json: constants.d.ts
packages/s/serializr.json: core/cancelDeserialize.d.ts
packages/s/serializr.json: core/Context.d.ts
packages/s/serializr.json: core/deserialize.d.ts
packages/s/serializr.json: core/serialize.d.ts
packages/s/serializr.json: core/serializeAll.d.ts
packages/s/serializr.json: core/update.d.ts
packages/s/serializr.json: es/serializr.js
packages/s/serializr.json: es/serializr.min.js
packages/s/serializr.json: serializr.d.ts
packages/s/serializr.json: serializr.js
packages/s/serializr.json: serializr.min.js
packages/s/serializr.json: types/alias.d.ts
packages/s/serializr.json: types/custom.d.ts
packages/s/serializr.json: types/date.d.ts
packages/s/serializr.json: types/identifier.d.ts
packages/s/serializr.json: types/list.d.ts
packages/s/serializr.json: types/map.d.ts
packages/s/serializr.json: types/mapAsArray.d.ts
packages/s/serializr.json: types/object.d.ts
packages/s/serializr.json: types/optional.d.ts
packages/s/serializr.json: types/poly.d.ts
packages/s/serializr.json: types/primitive.d.ts
packages/s/serializr.json: types/raw.d.ts
packages/s/serializr.json: types/reference.d.ts
packages/s/serializr.json: utils/invariant.d.ts
packages/s/serializr.json: utils/utils.d.ts
packages/s/serializr.json: 2.0.2:
packages/s/serializr.json: api/createModelSchema.d.ts
packages/s/serializr.json: api/createSimpleSchema.d.ts
packages/s/serializr.json: api/getDefaultModelSchema.d.ts
packages/s/serializr.json: api/serializable.d.ts
packages/s/serializr.json: api/setDefaultModelSchema.d.ts
packages/s/serializr.json: api/types.d.ts
packages/s/serializr.json: constants.d.ts
packages/s/serializr.json: core/cancelDeserialize.d.ts
packages/s/serializr.json: core/Context.d.ts
packages/s/serializr.json: core/deserialize.d.ts
packages/s/serializr.json: core/serialize.d.ts
packages/s/serializr.json: core/serializeAll.d.ts
packages/s/serializr.json: core/update.d.ts
packages/s/serializr.json: es/serializr.js
packages/s/serializr.json: es/serializr.min.js
packages/s/serializr.json: serializr.d.ts
packages/s/serializr.json: serializr.js
packages/s/serializr.json: serializr.min.js
packages/s/serializr.json: types/alias.d.ts
packages/s/serializr.json: types/custom.d.ts
packages/s/serializr.json: types/date.d.ts
packages/s/serializr.json: types/identifier.d.ts
packages/s/serializr.json: types/list.d.ts
packages/s/serializr.json: types/map.d.ts
packages/s/serializr.json: types/mapAsArray.d.ts
packages/s/serializr.json: types/object.d.ts
packages/s/serializr.json: types/optional.d.ts
packages/s/serializr.json: types/poly.d.ts
packages/s/serializr.json: types/primitive.d.ts
packages/s/serializr.json: types/raw.d.ts
packages/s/serializr.json: types/reference.d.ts
packages/s/serializr.json: utils/invariant.d.ts
packages/s/serializr.json: utils/utils.d.ts
packages/s/serializr.json: 2.0.3:
packages/s/serializr.json: api/createModelSchema.d.ts
packages/s/serializr.json: api/createSimpleSchema.d.ts
packages/s/serializr.json: api/getDefaultModelSchema.d.ts
packages/s/serializr.json: api/serializable.d.ts
packages/s/serializr.json: api/setDefaultModelSchema.d.ts
packages/s/serializr.json: api/types.d.ts
packages/s/serializr.json: constants.d.ts
packages/s/serializr.json: core/cancelDeserialize.d.ts
packages/s/serializr.json: core/Context.d.ts
packages/s/serializr.json: core/deserialize.d.ts
packages/s/serializr.json: core/serialize.d.ts
packages/s/serializr.json: core/serializeAll.d.ts
packages/s/serializr.json: core/update.d.ts
packages/s/serializr.json: es/serializr.js
packages/s/serializr.json: es/serializr.min.js
packages/s/serializr.json: serializr.d.ts
packages/s/serializr.json: serializr.js
packages/s/serializr.json: serializr.min.js
packages/s/serializr.json: types/alias.d.ts
packages/s/serializr.json: types/custom.d.ts
packages/s/serializr.json: types/date.d.ts
packages/s/serializr.json: types/identifier.d.ts
packages/s/serializr.json: types/list.d.ts
packages/s/serializr.json: types/map.d.ts
packages/s/serializr.json: types/mapAsArray.d.ts
packages/s/serializr.json: types/object.d.ts
packages/s/serializr.json: types/optional.d.ts
packages/s/serializr.json: types/primitive.d.ts
packages/s/serializr.json: types/raw.d.ts
packages/s/serializr.json: types/reference.d.ts
packages/s/serializr.json: utils/invariant.d.ts
packages/s/serializr.json: utils/utils.d.ts
```

**Comment by xtuc** [comment]
@robocdnjs was flaky :(

**Pull request merged**
