### PR TITLE
Update jquery-fullscreen-plugin w/ git auto-update

### PR DESCRIPTION
**Pull request by MattIPv4**
cc https://github.com/cdnjs/cdnjs/pull/13972

### CODE REVIEW

**Comment by MattIPv4** [comment]
@xtuc we've migrated git packages to here, but it seems the CI isn't ready for them?

**Comment by williamdes** [comment]
Ready to merge :rocket:

**Comment by williamdes** [comment]
https://cdnjs.com/libraries/jquery-fullscreen-plugin

The search engine is up to date but not the page, I assume some caching is done

**Comment by MattIPv4** [comment]
The bot will run later today which will push new versions to cdnjs/cdnjs. The site updater will then run later in the day which will list the files on the site.

**Pull request merged**
