### PR TITLE
Updated the keywords for the gd-sprest libraries.

### PR DESCRIPTION
**Pull request by gunjandatta**

### CODE REVIEW

**Comment by MattIPv4** [comment]
This PR has merge conflicts, the updates are not good as this cannot be merged. You must resolve the conflicts.

**Comment by gunjandatta** [comment]
I may have messed this up. Per the documentation, it said to remove the fork. So I don't think I can commit any changes. I'm sorry, this is all very new to me and is my first time doing a PR for CDNJS. I'm also unsure how long it takes for the lib to become available.

**Comment by MattIPv4** [comment]
Probably best to close this PR, create a new fork and then make your changes & a new PR.

As for time to the lib being added on cdnjs, @xtuc might be able to comment on that. (PR: https://github.com/cdnjs/packages/pull/115/files, no files yet: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/gd-sprest/)

**Comment by gunjandatta** [comment]
Closing and recreating a new PR.

**Comment by gunjandatta** [comment]
@xtuc, how does this lib make it over to the master/ajax/libs folder? Do I need to initiate another PR in the main cdnjs library? Did I miss something in the instructions?

**Comment by MattIPv4** [comment]
The bot will copy it over once it pulls down versioned files for the library. I guess the better question would be when exactly the bot will do that?

**Comment by gunjandatta** [comment]
As long as I've completed everything on my end, I'm good to go. Just wanted to make sure. Thank you.

**Pull request closed without merging**
