### PR TITLE
Update hyperapp w/ npm auto-update

### PR DESCRIPTION
**Pull request by jorgebucaran**
Hey! So, we changed how we publish Hyperapp. Now we just deploy an `index.js` that describes an ES module. 

I was also wondering if cdnjs still generates a minified version for us automatically. That would be nice.

### CODE REVIEW

**Comment by MattIPv4** [comment]
👋 cdnjs will minify JS files, but we do not perform any bundling, so if you're only shipping an es module, it will only work in modern browsers that support es modules natively -- I strongly recommend shipping pre-bundled cjs/umd versions alongside your es module for web usage.

**Comment by MattIPv4** [comment]
Let me know if you'd still like to ship this with es module support only and I'll be happy to approve/merge :)

**Comment by jorgebucaran** [comment]
> cdnjs will minify JS files

Amazing, that's great! 🎯

> it will only work in modern browsers that support es modules natively 

No problem! 🙆‍♂️  

The upcoming Hyperapp 2 will only support modern browsers. We provide the source, though, so it's possible to compile and polyfill for IE11 and even IE10.

Do you mind reviewing my PR? I don't know if my changes here are valid as I'm not familiar with cdnjs internals.

**Review by MattIPv4 — APPROVED** [review]
Lgtm

**Pull request merged**
