### PR TITLE
Add ruffle-rs w/ npm auto-update

### LINKED ISSUE #1605: Add: Ruffle.js
### Library name

ruffle-rs

### Library license

https://github.com/ruffle-rs/ruffle/blob/master/LICENSE.md

### Library source

https://www.npmjs.com/package/@ruffle-rs/ruffle

### Files to include

I'm pretty sure this isn't automated, but EVERYTHING.
- Only 13 files
- About 20mb

### PR DESCRIPTION
**Pull request by MattIPv4**
Adding ruffle-rs using npm auto-update from @ruffle-rs/ruffle.

Resolves #1605.

### CODE REVIEW

**Review by MattIPv4 — COMMENTED** [review]
lgtm

**Comment by chenxuuu** [comment]
seems [it stoped auto update](https://cdnjs.com/libraries/ruffle-rs), maybe it reach the max number of version?

**Comment by MattIPv4** [comment]
@xtuc any ideas? I see no logs for new versions in https://github.com/cdnjs/logs/tree/prod/packages/r/ruffle-rs, but there are definitely new versions at https://www.npmjs.com/package/@ruffle-rs/ruffle?activeTab=versions

**Comment by xiedada05** [comment]
It seems to stopped auto update has stopped again since September 2025, any ideas? Or you gave up maintaining this?

**Comment by MattIPv4** [comment]
@TimXiedada please see https://github.com/cdnjs/cdnjs/issues/14263 for updates on that.

**Pull request merged**
