### PR TITLE
Update vanilla-lazyload w/ git auto-update

### PR DESCRIPTION
**Pull request by jerryc127**

### CODE REVIEW

**Review by MattIPv4 — APPROVED** [review]
LGTM

**Comment by jerryc127** [comment]
The pull request was merged. 
why this package still not update to latest version in cdnjs ?

**Comment by MattIPv4** [comment]
🤔 Not sure -- @xtuc any ideas? [No logs at all](https://github.com/cdnjs/logs/tree/prod/packages/v/vanilla-lazyload), but there are definitely [versions we don't have](https://github.com/verlok/vanilla-lazyload/tags).

**Comment by jerryc127** [comment]
> 🤔 Not sure -- @xtuc any ideas? [No logs at all](https://github.com/cdnjs/logs/tree/prod/packages/v/vanilla-lazyload), but there are definitely [versions we don't have](https://github.com/verlok/vanilla-lazyload/tags).

emm.. maybe change source to npm ?

**Pull request merged**
