### PR TITLE
Add canvas-confetti w/ git auto-update

### PR DESCRIPTION
**Pull request by s-crypt**
idk if I am doing this right, but there is a first time for everything

### CODE REVIEW

**Comment by s-crypt** [comment]
@MattIPv4 Could I please get an approval so that the workflow can start?

**Review by MattIPv4 — APPROVED** [review]
Lgtm

**Comment by s-crypt** [comment]
Thank you! I will take note of the proper formatting next time I submit a package

**Comment by s-crypt** [comment]
@MattIPv4 Is there any reason that this has not been imported to cdnjs/cdnjs? From what I can read, there is a bot that checks things every two hours, but it has been two days.

**Comment by MattIPv4** [comment]
@s-crypt Normally that would be the case, yeah, but unfortunately we currently have the auto-update bot offline for some extended maintenance. I'll work with the team to see if we can run it once manually to catch this new package. You can follow along with the maintenance on our status page: https://status.cdnjs.com/

**Comment by s-crypt** [comment]
@MattIPv4 would there be any reason that this package has not been robot-ed in now that the bot is operational again?

**Comment by MattIPv4** [comment]
👋 The bot maintenance is not yet completed -- we have only rolled out the new version to a limited number of NPM-based packages, and do not yet have support for git in the new bot. The bot is still marked as under maintenance on our status page.

**Comment by s-crypt** [comment]
Thanks! I saw the banner go away for a little bit and now it does not have a description, so I thought it was a bug. Good to know!

**Pull request merged**
