### PR TITLE
Add argon-dashboard w/ npm auto-update 

### PR DESCRIPTION
**Pull request by am-abudu**

### CODE REVIEW

**Comment by am-abudu** [comment]
how can i fix "Filename `argon-dashboard.min.js` not found in most recent version `2.0.4`. "?
it's in assets/js/argon-dashboard.min.js

**Comment by MattIPv4** [comment]
👀 Your preview commit was correct -- it looks like you're running into a bug with the CI though that is causing it to fail before all the assets are extracted, which is then resulting it claiming the file doesn't exist when it does.

If you can revert the commit you've just made, I can look at manually merging this when I have some time to validate it locally.

**Comment by am-abudu** [comment]
Thank you a lot. I have reverted it.

**Review by MattIPv4 — APPROVED** [review]
LGTM based on [glob-tool](https://www.digitalocean.com/community/tools/glob#?comments=true&glob=assets%2F%7B%40%28css%7Cfonts%7Cimg%29%2F%2A%2A%2F%2A.%40%28js%7Ccss%7Cttf%7Cwoff%7Cwoff2%7Ceot%7Csvg%7Cjpg%7Cjpeg%7Cpng%29%2Cjs%2F%7B%2Cplugins%2F%2Ccore%2F%7D%2A.js%7D&matches=false&tests=%2F%2F%20Imported%20from%20%40creative-tim-official%2Fargon-dashboard%20NPM%20package&tests=assets%2Fcss%2Fargon-dashboard.css&tests=assets%2Fcss%2Fargon-dashboard.min.css&tests=assets%2Fcss%2Fnucleo-icons.css&tests=assets%2Fcss%2Fnucleo-svg.css&tests=assets%2Ffonts%2Fnucleo-icons.eot&tests=assets%2Ffonts%2Fnucleo.eot&tests=pages%2Fbilling.html&tests=pages%2Fdashboard.html&tests=docs%2Fdocumentation.html&tests=index.html&tests=pages%2Fprofile.html&tests=pages%2Frtl.html&tests=pages%2Fsign-in.html&tests=pages%2Fsign-up.html&tests=pages%2Ftables.html&tests=pages%2Fvirtual-reality.html&tests=assets%2Fimg%2Ftheme%2Fspotify.jpeg&tests=assets%2Fimg%2Fcurved-images%2Fwhite-curved.jpeg&tests=assets%2Fimg%2Ftheme%2Fangular.jpg&tests=assets%2Fimg%2Fbg-profile.jpg&tests=assets%2Fimg%2Fbg1.jpg&tests=assets%2Fimg%2Ftheme%2Fbootstrap.jpg&tests=assets%2Fimg%2Fbruce-mars.jpg&tests=assets%2Fimg%2Fcarousel-1.jpg&tests=assets%2Fimg%2Fcarousel-2.jpg&tests=assets%2Fimg%2Fcarousel-3.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved-10.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved-11.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved-6.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved-8.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved0.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved1.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved10.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved11-small.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved11.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved12.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved13.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved14.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved19.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved2.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved21.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved3.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved4.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved5-small.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved5.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved6-small.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved6.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved7.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved8.jpg&tests=assets%2Fimg%2Fcurved-images%2Fcurved9.jpg&tests=assets%2Fimg%2Fhome-decor-1.jpg&tests=assets%2Fimg%2Fhome-decor-2.jpg&tests=assets%2Fimg%2Fhome-decor-3.jpg&tests=assets%2Fimg%2Fivana-square.jpg&tests=assets%2Fimg%2Fivancik.jpg&tests=assets%2Fimg%2Fkal-visuals-square.jpg&tests=assets%2Fimg%2Fmarie.jpg&tests=assets%2Fimg%2Ftheme%2Freact.jpg&tests=assets%2Fimg%2Ftheme%2Fsketch.jpg&tests=assets%2Fimg%2Fteam-1.jpg&tests=assets%2Fimg%2Fteam-2.jpg&tests=assets%2Fimg%2Fteam-3.jpg&tests=assets%2Fimg%2Fteam-4.jpg&tests=assets%2Fimg%2Ftheme%2Funass.jpg&tests=assets%2Fimg%2Fvr-bg.jpg&tests=assets%2Fimg%2Ftheme%2Fvue.jpg&tests=assets%2Fjs%2Fargon-dashboard.js&tests=assets%2Fjs%2Fargon-dashboard.min.js&tests=assets%2Fjs%2Fplugins%2Fbootstrap-notify.js&tests=assets%2Fjs%2Fcore%2Fbootstrap.bundle.min.js&tests=assets%2Fjs%2Fcore%2Fbootstrap.min.js&tests=assets%2Fjs%2Fplugins%2FChart.extension.js&tests=assets%2Fjs%2Fplugins%2Fchartjs.min.js&tests=gulpfile.js&tests=assets%2Fjs%2Fplugins%2Fperfect-scrollbar.min.js&tests=assets%2Fjs%2Fcore%2Fpopper.min.js&tests=assets%2Fjs%2Fplugins%2Fsmooth-scrollbar.min.js&tests=package.json&tests=assets%2Fcss%2Fargon-dashboard.css.map&tests=assets%2Fjs%2Fargon-dashboard.js.map&tests=CHANGELOG.md&tests=ISSUE_TEMPLATE.md&tests=LICENSE.md&tests=README.md&tests=assets%2Fimg%2Fapple-icon.png&tests=assets%2Fimg%2Ficons%2Fflags%2FAU.png&tests=assets%2Fimg%2Ficons%2Fflags%2FBR.png&tests=assets%2Fimg%2Ficons%2Fflags%2FDE.png&tests=assets%2Fimg%2Ftheme%2Fdribbble.png&tests=assets%2Fimg%2Ftheme%2Fdropbox.png&tests=assets%2Fimg%2Ffavicon.png&tests=assets%2Fimg%2Ficons%2Fflags%2FGB.png&tests=assets%2Fimg%2Fsmall-logos%2Ficon-sun-cloud.png&tests=assets%2Fimg%2Flogo-ct-dark.png&tests=assets%2Fimg%2Flogo-ct.png&tests=assets%2Fimg%2Flogos%2Fmastercard.png&tests=assets%2Fimg%2Ftheme%2Fmastercard.png&tests=assets%2Fimg%2Ftheme%2Fpaypal.png&tests=assets%2Fimg%2Fillustrations%2Frocket-white.png&tests=assets%2Fimg%2Ftheme%2Fslack.png&tests=assets%2Fimg%2Ftheme%2Ftim.png&tests=assets%2Fimg%2Ficons%2Fflags%2FUS.png&tests=assets%2Fimg%2Flogos%2Fvisa.png&tests=assets%2Fimg%2Ftheme%2Fvisa.png&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_accordion.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_alert.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_alert.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_alert.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_animations.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Futilities%2F_api.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_avatars.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_avatars.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_backdrop.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_badge.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_badge.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fmixins%2F_badge.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_badge.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_border-radius.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_box-shadow.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_breadcrumb.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_breadcrumb.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_breadcrumbs.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_breakpoints.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_button-group.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_buttons.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_buttons.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_buttons.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_card.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_cards-extend.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_cards.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_cards.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_caret.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_carousel.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_choices.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fhelpers%2F_clearfix.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_clearfix.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_close.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fhelpers%2F_color-bg.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_color-scheme.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fhelpers%2F_colored-links.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fmixins%2F_colored-shadows.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_container.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_containers.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_dark-version.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_dark-version.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_deprecate.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_dropdown.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_dropdown.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_dropdowns.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_dropup.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_fixed-plugin.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_fixed-plugin.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fplugins%2Ffree%2F_flatpickr.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fforms%2F_floating-labels.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_footer.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fforms%2F_form-check.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fforms%2F_form-check.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fforms%2F_form-control.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fforms%2F_form-range.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fforms%2F_form-select.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fforms%2F_form-select.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fforms%2F_form-switch.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_form-switch.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fforms%2F_form-text.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_forms.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_forms.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_forms.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fforms%2F_forms.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_full-calendar.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_functions.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_gradients.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_gradients.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_grid.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_grid.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_header.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_header.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_helpers.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fmixins%2F_hover.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_image.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_images.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_info-areas.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_info-areas.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fforms%2F_input-group.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fforms%2F_input-group.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fforms%2F_inputs.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fforms%2F_labels.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fforms%2F_labels.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_list-group.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_list-group.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_lists.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_maps.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_misc-extend.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_misc.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_misc.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_mixins.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_modal.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_nav.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_nav.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_navbar-vertical.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_navbar-vertical.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_navbar.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_navbar.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_navbar.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fplugins%2Ffree%2F_nouislider.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_offcanvas.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_pagination.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_pagination.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_pagination.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_pagination.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fplugins%2Ffree%2F_perfect-scrollbar.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_placeholders.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_popover.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_popovers.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fhelpers%2F_position.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fplugins%2Ffree%2F_prism.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_progress.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_progress.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fhelpers%2F_ratio.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_reboot.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_reset-text.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_resize.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fvendor%2F_rfs.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_root.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_rtl.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_rtl.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_social-buttons.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fmixins%2F_social-buttons.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_social-buttons.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_spinners.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fhelpers%2F_stacks.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fhelpers%2F_stretched-link.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fcustom%2F_styles.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_table-variants.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_table.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_tables.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_tables.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_text-truncate.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fhelpers%2F_text-truncation.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_tilt.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_timeline.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_timeline.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_toasts.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_tooltip.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_tooltips.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_transition.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_transitions.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_type.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_typography.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_utilities-extend.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_utilities-extend.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_utilities.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_utilities.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_utilities.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_utilities.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fforms%2F_validation.scss&tests=assets%2Fscss%2Fargon-dashboard%2F_variables.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2F_variables.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fcustom%2F_variables.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fvariables%2F_virtual-reality.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fhelpers%2F_visually-hidden.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fmixins%2F_visually-hidden.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fhelpers%2F_vr.scss&tests=assets%2Fscss%2Fargon-dashboard.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fbootstrap-grid.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fbootstrap-reboot.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fbootstrap-utilities.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fbootstrap%2Fbootstrap.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fcards%2Fcard-background.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fcards%2Fcard-carousel.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fmixins%2Fmixins.scss&tests=assets%2Fscss%2Fargon-dashboard%2Fplugins%2Ffree%2Fplugins.scss&tests=assets%2Fscss%2Fargon-dashboard%2Ftheme.scss&tests=assets%2Fimg%2Fdown-arrow-dark.svg&tests=assets%2Fimg%2Fdown-arrow-white.svg&tests=assets%2Fimg%2Fdown-arrow.svg&tests=assets%2Fimg%2Fillustrations%2Ficon-documentation.svg&tests=assets%2Fimg%2Fsmall-logos%2Flogo-atlassian.svg&tests=assets%2Fimg%2Fsmall-logos%2Flogo-invision.svg&tests=assets%2Fimg%2Fsmall-logos%2Flogo-jira.svg&tests=assets%2Fimg%2Fsmall-logos%2Flogo-slack.svg&tests=assets%2Fimg%2Fsmall-logos%2Flogo-spotify.svg&tests=assets%2Fimg%2Fsmall-logos%2Flogo-webdev.svg&tests=assets%2Fimg%2Fsmall-logos%2Flogo-xd.svg&tests=assets%2Ffonts%2Fnucleo-icons.svg&tests=assets%2Fimg%2Fshapes%2Fpattern-lines.svg&tests=assets%2Fimg%2Fshapes%2Fshape-1.svg&tests=assets%2Fimg%2Fshapes%2Fshape-2.svg&tests=assets%2Fimg%2Fshapes%2Fshape-3.svg&tests=assets%2Fimg%2Fshapes%2Fwave-down.svg&tests=assets%2Fimg%2Fshapes%2Fwave-up.svg&tests=assets%2Fimg%2Fshapes%2Fwaves-gray.svg&tests=assets%2Fimg%2Fshapes%2Fwaves-white.svg&tests=assets%2Ffonts%2Fnucleo-icons.ttf&tests=assets%2Ffonts%2Fnucleo.ttf&tests=assets%2Ffonts%2Fnucleo-icons.woff&tests=assets%2Ffonts%2Fnucleo.woff&tests=assets%2Ffonts%2Fnucleo-icons.woff2&tests=assets%2Ffonts%2Fnucleo.woff2&tests=.github%2Fworkflows%2Fmain.yml), ignoring CI error (failing due to a compression issue)

**Pull request merged**
