### PR TITLE
Add natsort w/ npm auto-update

### PR DESCRIPTION
**Pull request by MattIPv4**
Adding natsort using npm auto-update from NPM package natsort.

Resolves https://github.com/cdnjs/cdnjs/issues/12369.

### CODE REVIEW

**Comment by robocdnjs** [comment]
**Tests passed.**
Preview for `packages/n/natsort.json`
Last version (2.0.2):
```
natsort.min.js
```
10 Last version:
```
2.0.2: 1 file(s) matched
match *.js in /tmp/npmtarball266316283/dist but doesn't exists
2.0.0: 0 file(s) matched
match *.js in /tmp/npmtarball003345182/dist but doesn't exists
1.0.6: 0 file(s) matched
match *.js in /tmp/npmtarball249391077/dist but doesn't exists
1.0.5: 0 file(s) matched
match *.js in /tmp/npmtarball891288576/dist but doesn't exists
1.0.4: 0 file(s) matched
match *.js in /tmp/npmtarball232519007/dist but doesn't exists
1.0.3: 0 file(s) matched
match *.js in /tmp/npmtarball160587058/dist but doesn't exists
1.0.2: 0 file(s) matched
match *.js in /tmp/npmtarball645022953/dist but doesn't exists
1.0.1: 0 file(s) matched
match *.js in /tmp/npmtarball128626996/dist but doesn't exists
1.0.0: 0 file(s) matched
match *.js in /tmp/npmtarball953250051/dist but doesn't exists
0.0.1: 0 file(s) matched
```

**Comment by robocdnjs** [comment]
**Tests passed.**
Preview for `packages/n/natsort.json`
Last version (2.0.2):
```
natsort.min.js
```
10 Last version:
```
2.0.2: 1 file(s) matched
match *.js in /tmp/npmtarball581960093/dist but doesn't exists
2.0.0: 0 file(s) matched
match *.js in /tmp/npmtarball213765208/dist but doesn't exists
1.0.6: 0 file(s) matched
match *.js in /tmp/npmtarball815613911/dist but doesn't exists
1.0.5: 0 file(s) matched
match *.js in /tmp/npmtarball870151498/dist but doesn't exists
1.0.4: 0 file(s) matched
match *.js in /tmp/npmtarball783883809/dist but doesn't exists
1.0.3: 0 file(s) matched
match *.js in /tmp/npmtarball160924940/dist but doesn't exists
1.0.2: 0 file(s) matched
match *.js in /tmp/npmtarball582842619/dist but doesn't exists
1.0.1: 0 file(s) matched
match *.js in /tmp/npmtarball156040734/dist but doesn't exists
1.0.0: 0 file(s) matched
match *.js in /tmp/npmtarball072941797/dist but doesn't exists
0.0.1: 0 file(s) matched
```

**Comment by MattIPv4** [comment]
Older versions didn't have an included dist file, nothing we can do about that ^

**Comment by xtuc** [comment]
Yeah I suspected that, I was checking if it wasn't flaky.

**Pull request merged**
