### PR TITLE
Add js-pytorch w/ npm auto-update

### PR DESCRIPTION
**Pull request by eduardoleao052**
Deep Learning JavaScript library with PyTorch's syntax, and GPU acceleration.

### CODE REVIEW

**Review by MattIPv4 — APPROVED** [review]
LGTM

**Comment by eduardoleao052** [comment]
Thanks!
I have a small doubt, if you have the time. Will the `script tag` and `url` be automatically added to the `cdnjs` website, or do I need to do something about it?
The page is currently [like this](https://cdnjs.com/libraries/js-pytorch).
Thanks in advance!

**Comment by MattIPv4** [comment]
You'll need to wait for it to [finish publishing the existing versions](https://github.com/cdnjs/logs/tree/prod/packages/j/js-pytorch) -- the config you provided is only valid for the most recent version, the browser file didn't exist for older versions.

**Comment by eduardoleao052** [comment]
Ok, I understand. So I don't need to change anything?
Thanks again!

**Pull request merged**
