### PR TITLE
Add hexo-theme-volantis w/ npm auto-update

### LINKED ISSUE #1278: Add: hexo-theme-volantis
### Library name

hexo-theme-volantis

### Library license

https://github.com/volantis-x/hexo-theme-volantis/blob/dev/LICENSE

### Library source

https://www.npmjs.com/package/hexo-theme-volantis

### Files to include

- source/**/*.css
- source/**/*.js

### PR DESCRIPTION
**Pull request by MHuiG**
Adding hexo-theme-volantis using npm auto-update from hexo-theme-volantis.

Resolves #1278.

### CODE REVIEW

**Comment by MHuiG** [comment]
After this repository was pulled down, there are three modified files but no commits, I don't know why this appears.

image

**Comment by MattIPv4** [comment]
Because your system does not allow files of the same name with different casing. See https://github.com/cdnjs/cdnjs/issues/3650

**Comment by MHuiG** [comment]
Does the "filename" of the json file have to be the same as the "name" key of the json file?
Maybe it's possible to just use the "name" key of that json file instead of relying on the "filename" of the json file.

**Comment by MattIPv4** [comment]
`filename` should be the name of the default file within your project that users should include in their webpage to get started using your library, for example `index.js`

**Review by MattIPv4 — APPROVED** [review]
LGTM

**Pull request merged**
