### PR TITLE
Update alasql w/ npm auto-update

### PR DESCRIPTION
**Pull request by mathiasrw**
The repo for AlaSQL was moved to the AlaSQL organisation on Github.

### CODE REVIEW

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
👋 It looks like the repository (https://github.com/AlaSQL/alasql/tree/v2.1.3) no longer contains the `dist` directory -- should this be switched over to pulling from NPM instead of Git?

**Comment by mathiasrw** [comment]
Ahhh - good point! Ill try to make it point to NPM

**Comment by mathiasrw** [comment]
Ok - I think I got it. Please review and let me know if I should do better...

**Review by MattIPv4 — APPROVED** [review]
LGTM, ty

**Pull request merged**
